server:
  port: 8082
  servlet:
    context-path: /api
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: mysql123
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

minio:
  endpoint: http://localhost:9000
  accessKey: minio
  secretKey: minio123

ip: localhost
